import type { Metadata } from "next";
import { RecoilContextProvider } from "./recoilContextProvider";
import { Providers } from "./providers";
import Navbar from "./components/Navbar/";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilContextProvider>
          <Providers>
            <Navbar />
            <main>{children}</main>
          </Providers>
        </RecoilContextProvider>
      </body>
    </html>
    
  );
};
